import React, { useState, useEffect, useRef } from 'react';
import { AstraStatus, AppId, FileItem, NoteItem, TerminalLog, AutomationStep, VoiceSettings, AstraCommandResult } from './types';
import { AstraHeader } from './components/AstraHeader';
import { AstraCommandBar } from './components/AstraCommandBar';
import { DesktopWorkstation } from './components/DesktopWorkstation';
import { tts, VoiceListener, chime } from './utils/speech';

// Default starter files for the simulated PC
const INITIAL_FILES: FileItem[] = [
  {
    id: 'f-1',
    name: 'index.html',
    path: '/Portfolio/index.html',
    type: 'file',
    language: 'html',
    size: 420,
    updatedAt: 'Just now',
    content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Portfolio - Created by Astra AI</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div className="container">
    <h1>Welcome to My Portfolio</h1>
    <p>Automated & Generated by Astra AI Voice Assistant.</p>
    <button id="btn">Click Me</button>
  </div>
  <script src="script.js"></script>
</body>
</html>`
  },
  {
    id: 'f-2',
    name: 'style.css',
    path: '/Portfolio/style.css',
    type: 'file',
    language: 'css',
    size: 280,
    updatedAt: 'Just now',
    content: `body {
  font-family: 'Segoe UI', system-ui, sans-serif;
  background-color: #0f172a;
  color: #f8fafc;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  margin: 0;
}
.container {
  text-align: center;
  padding: 2rem;
  background: #1e293b;
  border-radius: 1rem;
  box-shadow: 0 10px 25px rgba(0,0,0,0.5);
}
button {
  background: #0ea5e9;
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 0.5rem;
  cursor: pointer;
  font-weight: bold;
}`
  },
  {
    id: 'f-3',
    name: 'script.js',
    path: '/Portfolio/script.js',
    type: 'file',
    language: 'javascript',
    size: 150,
    updatedAt: 'Just now',
    content: `document.addEventListener('DOMContentLoaded', () => {
  const btn = document.getElementById('btn');
  btn?.addEventListener('click', () => {
    alert('Astra Voice Assistant automation script working!');
  });
});`
  }
];

const INITIAL_NOTES: NoteItem[] = [
  {
    id: 'n-1',
    title: 'Astra AI Voice Commands Guide',
    content: `Say "Astra" to wake up Astra.
Astra will respond: "Yes Sir, tell me."
Then state any command, e.g.:
"Open VS Code, create an HTML project named Portfolio, generate index.html, style.css and script.js, write starter code, save all files and open Live Server."
Astra will automate everything and reply: "Done, Sir."`,
    category: 'Instructions',
    timestamp: 'Today, 09:00 AM'
  }
];

const INITIAL_LOGS: TerminalLog[] = [
  {
    id: 'l-1',
    command: 'astra --version',
    output: 'Astra AI System Voice Automation Daemon v2.4.0 [Active]',
    type: 'system',
    timestamp: '09:00:00'
  }
];

export default function App() {
  // Voice & Assistant State
  const [status, setStatus] = useState<AstraStatus>('listening_wake_word');
  const [speechResponseText, setSpeechResponseText] = useState<string>('');
  const [transcript, setTranscript] = useState<string>('');
  const [isListening, setIsListening] = useState<boolean>(false);

  const [voiceSettings, setVoiceSettings] = useState<VoiceSettings>({
    wakeWord: 'Astra',
    ttsEnabled: true,
    speechRate: 1.0,
    speechPitch: 1.0,
    selectedVoiceName: '',
    autoExecute: true,
    permissionGranted: true,
  });

  // Active Applications & Workspace State
  const [activeApps, setActiveApps] = useState<AppId[]>(['vscode', 'chrome', 'youtube', 'explorer', 'terminal', 'notes']);
  const [activeAppId, setActiveAppId] = useState<AppId>('vscode');

  // Workspace Files, Notes, Terminal Logs, Browser URL, YouTube Music
  const [files, setFiles] = useState<FileItem[]>(INITIAL_FILES);
  const [activeFilePath, setActiveFilePath] = useState<string | null>('/Portfolio/index.html');
  const [notes, setNotes] = useState<NoteItem[]>(INITIAL_NOTES);
  const [terminalLogs, setTerminalLogs] = useState<TerminalLog[]>(INITIAL_LOGS);
  const [browserUrl, setBrowserUrl] = useState<string>('http://localhost:5500');
  const [youtubeSearchQuery, setYoutubeSearchQuery] = useState<string>('Hindi song');
  const [isLiveServerRunning, setIsLiveServerRunning] = useState<boolean>(true);

  // Automation Execution Stream
  const [automationSteps, setAutomationSteps] = useState<AutomationStep[]>([]);
  const [currentStepIndex, setCurrentStepIndex] = useState<number>(0);
  const [isExecuting, setIsExecuting] = useState<boolean>(false);

  const listenerRef = useRef<VoiceListener | null>(null);

  // Initialize Speech Listener
  useEffect(() => {
    listenerRef.current = new VoiceListener();
  }, []);

  // Voice Speaking Helper
  const speakText = async (text: string) => {
    setSpeechResponseText(text);
    if (voiceSettings.ttsEnabled) {
      await tts.speak(text, {
        rate: voiceSettings.speechRate,
        pitch: voiceSettings.speechPitch,
        voiceName: voiceSettings.selectedVoiceName,
      });
    }
  };

  // Wake Word Trigger Handler ("Astra" -> "Yes Sir, tell me.")
  const handleWakeAstra = async () => {
    chime.playChime('wake');
    setStatus('wake_word_detected');
    await speakText("Yes Sir, tell me.");
    setStatus('listening_command');
  };

  // Start Mic Listening
  const handleStartListening = () => {
    if (!listenerRef.current) return;
    setIsListening(true);
    setStatus('listening_wake_word');

    listenerRef.current.start((text, isFinal) => {
      setTranscript(text);
      const lower = text.toLowerCase();
      const wakeWordLower = voiceSettings.wakeWord.toLowerCase();

      // Check if user said "Astra" or similar wake word
      if (
        lower.includes(wakeWordLower) ||
        lower.includes('hey astra') ||
        lower.includes('ok astra') ||
        lower.includes('estrah') ||
        lower.includes('astro')
      ) {
        handleWakeAstra();
        // Remove wake word from transcript to isolate command
        const cleanedCmd = text.replace(new RegExp(wakeWordLower, 'gi'), '').trim();
        if (cleanedCmd.length > 3) {
          handleExecuteCommand(cleanedCmd);
        }
      } else if (status === 'listening_command') {
        if (isFinal && text.trim()) {
          handleExecuteCommand(text.trim());
        }
      }
    });
  };

  const handleStopListening = () => {
    if (listenerRef.current) {
      listenerRef.current.stop();
    }
    setIsListening(false);
    setStatus('idle');
  };

  // Process User Command with Gemini AI Server Endpoint
  const handleExecuteCommand = async (commandStr: string) => {
    setStatus('processing');
    setTranscript(commandStr);

    const cmdLower = commandStr.toLowerCase();
    const isMusicQuery = cmdLower.includes('song') || 
                         cmdLower.includes('bhojpuri') || 
                         cmdLower.includes('hindi') || 
                         cmdLower.includes('kahoon') || 
                         cmdLower.includes('sonu') || 
                         cmdLower.includes('pawan') || 
                         cmdLower.includes('arijit') || 
                         cmdLower.includes('youtube') || 
                         cmdLower.includes('music') ||
                         cmdLower.startsWith('play ');

    if (isMusicQuery) {
      setActiveApps(prev => prev.includes('youtube') ? prev : [...prev, 'youtube']);
      setActiveAppId('youtube');
      const cleanedSong = commandStr.replace(/play|astra|song|on youtube|please|can you/gi, '').trim() || commandStr;
      setYoutubeSearchQuery(cleanedSong);
    }

    let parsed: AstraCommandResult;
    try {
      const response = await fetch('/api/astra/parse-command', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          command: commandStr,
          activeContext: {
            activeApps,
            activeAppId,
            fileCount: files.length,
            isLiveServerRunning,
            browserUrl
          }
        })
      });

      const json = await response.json();
      if (json.success && json.data) {
        parsed = json.data;
      } else {
        throw new Error(json.error || "Server parse failed");
      }
    } catch (err) {
      console.warn("Using client-side Astra command fallback:", err);
      const songName = commandStr.replace(/play|astra|song|on youtube|please|can you/gi, '').trim() || commandStr;
      if (isMusicQuery) {
        parsed = {
          isUnclear: false,
          confirmationMessage: "Done, Sir.",
          targetApps: ["youtube"],
          summary: `Playing "${songName}" on YouTube.`,
          steps: [
            {
              title: "Open YouTube Music Player",
              description: `Streaming YouTube audio for ${songName}`,
              app: "youtube",
              actionType: "play_youtube",
              payload: { searchQuery: songName }
            }
          ]
        };
      } else {
        parsed = {
          isUnclear: false,
          confirmationMessage: "Done, Sir.",
          targetApps: [activeAppId || "vscode"],
          summary: `Automating command: "${commandStr}"`,
          steps: [
            {
              title: `Process ${commandStr}`,
              description: `Completed action for: ${commandStr}`,
              app: activeAppId || "vscode",
              actionType: "open_app",
              payload: {}
            }
          ]
        };
      }
    }

    try {
      if (parsed.isUnclear && parsed.followUpQuestion) {
        setStatus('clarifying');
        await speakText(parsed.followUpQuestion);
        return;
      }

      // Populate Automation Steps
      const formattedSteps: AutomationStep[] = parsed.steps.map((s, idx) => ({
        id: `step-${idx}-${Date.now()}`,
        title: s.title,
        description: s.description,
        app: s.app,
        actionType: s.actionType,
        status: 'pending',
        details: s.payload,
        payload: s.payload
      }));

      setAutomationSteps(formattedSteps);
      setCurrentStepIndex(0);
      setIsExecuting(true);
      setStatus('executing');

      // Execute steps in sequence
      for (let i = 0; i < formattedSteps.length; i++) {
        setCurrentStepIndex(i);
        const step = formattedSteps[i];

        // Ensure target app is open and brought to focus
        if (step.app && !activeApps.includes(step.app)) {
          setActiveApps(prev => [...prev, step.app]);
        }
        if (step.app) {
          setActiveAppId(step.app);
        }

        // Handle YouTube Play Action or Music Search
        if (
          step.actionType === 'play_youtube' ||
          step.app === 'youtube' ||
          (step.payload?.searchQuery && (
            step.payload.searchQuery.toLowerCase().includes('song') ||
            step.payload.searchQuery.toLowerCase().includes('bhojpuri') ||
            step.payload.searchQuery.toLowerCase().includes('hindi') ||
            step.payload.searchQuery.toLowerCase().includes('youtube')
          ))
        ) {
          setActiveApps(prev => prev.includes('youtube') ? prev : [...prev, 'youtube']);
          setActiveAppId('youtube');
          const songQuery = step.payload?.searchQuery || step.payload?.webUrl || commandStr;
          setYoutubeSearchQuery(songQuery);
        }

        // Perform specific desktop action based on step payload
        if (step.payload) {
          const { fileName, filePath, fileContent, folderName, terminalCommand, searchQuery, webUrl, noteTitle, noteContent } = step.payload;

          if (fileName || filePath) {
            const targetPath = filePath || `/${folderName || 'Portfolio'}/${fileName}`;
            const targetName = fileName || (targetPath.split('/').pop() || 'file.txt');
            
            // Add/update file in workspace
            setFiles(prev => {
              const existingIdx = prev.findIndex(f => f.path === targetPath);
              const newFileObj: FileItem = {
                id: `file-${Date.now()}-${Math.random()}`,
                name: targetName,
                path: targetPath,
                type: 'file',
                language: targetName.endsWith('.html') ? 'html' : targetName.endsWith('.css') ? 'css' : targetName.endsWith('.js') ? 'javascript' : 'text',
                content: fileContent || `// ${targetName} created by Astra AI`,
                size: (fileContent || '').length || 200,
                updatedAt: 'Just now'
              };

              if (existingIdx >= 0) {
                const updated = [...prev];
                updated[existingIdx] = newFileObj;
                return updated;
              } else {
                return [...prev, newFileObj];
              }
            });

            setActiveFilePath(targetPath);
          }

          if (terminalCommand) {
            setTerminalLogs(prev => [
              ...prev,
              {
                id: `log-${Date.now()}`,
                command: terminalCommand,
                output: `Executed command successfully: ${terminalCommand}`,
                type: 'success',
                timestamp: new Date().toLocaleTimeString()
              }
            ]);
          }

          if (searchQuery) {
            setBrowserUrl(`https://www.google.com/search?q=${encodeURIComponent(searchQuery)}`);
          } else if (webUrl) {
            setBrowserUrl(webUrl);
          }

          if (noteTitle && noteContent) {
            setNotes(prev => [
              {
                id: `note-${Date.now()}`,
                title: noteTitle,
                content: noteContent,
                category: 'Voice Automation',
                timestamp: 'Just now'
              },
              ...prev
            ]);
          }
        }

        // If command mentions Live Server
        if (step.actionType === 'open_url' || step.description.toLowerCase().includes('live server')) {
          setIsLiveServerRunning(true);
          setBrowserUrl('http://localhost:5500');
        }

        // Pause briefly between steps for visible realistic execution animation
        await new Promise(res => setTimeout(res, 900));
      }

      setIsExecuting(false);
      setStatus('completed');
      chime.playChime('complete');

      // Final verbal confirmation: "Done, Sir."
      const confirmPhrase = parsed.confirmationMessage || "Done, Sir.";
      await speakText(confirmPhrase);

    } catch (err: any) {
      console.error("Error executing command:", err);
      setStatus('error');
      await speakText("Sir, I encountered an issue executing that command.");
    }
  };

  // Handlers for File & Workspace Operations
  const handleSelectFile = (path: string) => {
    setActiveFilePath(path);
  };

  const handleSaveFile = (path: string, newContent: string) => {
    setFiles(prev => prev.map(f => f.path === path ? { ...f, content: newContent, updatedAt: 'Just now' } : f));
  };

  const handleCreateFile = (name: string, isFolder: boolean) => {
    const path = `/Portfolio/${name}`;
    setFiles(prev => [
      ...prev,
      {
        id: `f-${Date.now()}`,
        name,
        path,
        type: isFolder ? 'folder' : 'file',
        language: name.endsWith('.html') ? 'html' : name.endsWith('.css') ? 'css' : 'javascript',
        content: isFolder ? '' : `// ${name}`,
        size: 100,
        updatedAt: 'Just now'
      }
    ]);
  };

  const handleDeleteFile = (path: string) => {
    setFiles(prev => prev.filter(f => f.path !== path));
    if (activeFilePath === path) {
      setActiveFilePath(files[0]?.path || null);
    }
  };

  // Notes Handlers
  const handleCreateNote = (title: string, content: string, category = 'General') => {
    setNotes(prev => [
      {
        id: `note-${Date.now()}`,
        title,
        content,
        category,
        timestamp: 'Just now'
      },
      ...prev
    ]);
  };

  const handleDeleteNote = (id: string) => {
    setNotes(prev => prev.filter(n => n.id !== id));
  };

  // Terminal Handlers
  const handleExecuteTerminalCmd = (cmd: string) => {
    let output = `Command executed: ${cmd}`;
    if (cmd.includes('ls')) {
      output = files.map(f => f.name).join('   ');
    } else if (cmd.includes('mkdir')) {
      output = `Directory created: ${cmd.split(' ')[1] || 'NewFolder'}`;
    } else if (cmd.includes('npm')) {
      output = `npm package manager initialized successfully.`;
    } else if (cmd.includes('live-server')) {
      setIsLiveServerRunning(true);
      setBrowserUrl('http://localhost:5500');
      output = `[Live Server] Serving at http://localhost:5500`;
    }

    setTerminalLogs(prev => [
      ...prev,
      {
        id: `l-${Date.now()}`,
        command: cmd,
        output,
        type: 'output',
        timestamp: new Date().toLocaleTimeString()
      }
    ]);
  };

  return (
    <div className="flex flex-col h-screen w-screen bg-slate-950 text-slate-100 font-sans overflow-hidden">
      {/* Header with Astra Voice Indicator & Settings */}
      <AstraHeader
        status={status}
        voiceSettings={voiceSettings}
        onUpdateSettings={(updated) => setVoiceSettings(prev => ({ ...prev, ...updated }))}
        onManualWake={handleWakeAstra}
        activeAppCount={activeApps.length}
      />

      {/* Voice Input & Command Bar */}
      <AstraCommandBar
        status={status}
        transcript={transcript}
        isListening={isListening}
        onStartListening={handleStartListening}
        onStopListening={handleStopListening}
        onSubmitCommand={handleExecuteCommand}
        onWakeAstra={handleWakeAstra}
        speechResponseText={speechResponseText}
      />

      {/* Main Desktop Workstation & Windows Stage */}
      <DesktopWorkstation
        activeApps={activeApps}
        onOpenApp={(app) => {
          if (!activeApps.includes(app)) setActiveApps([...activeApps, app]);
          setActiveAppId(app);
        }}
        onCloseApp={(app) => {
          const remaining = activeApps.filter(a => a !== app);
          setActiveApps(remaining);
          if (activeAppId === app && remaining.length > 0) {
            setActiveAppId(remaining[remaining.length - 1]);
          }
        }}
        activeAppId={activeAppId}
        onSetActiveApp={setActiveAppId}
        youtubeSearchQuery={youtubeSearchQuery}
        onSearchYouTube={setYoutubeSearchQuery}
        files={files}
        activeFilePath={activeFilePath}
        onSelectFile={handleSelectFile}
        onSaveFile={handleSaveFile}
        onCreateFile={handleCreateFile}
        onDeleteFile={handleDeleteFile}
        notes={notes}
        onCreateNote={handleCreateNote}
        onDeleteNote={handleDeleteNote}
        terminalLogs={terminalLogs}
        onExecuteTerminalCmd={handleExecuteTerminalCmd}
        onClearTerminalLogs={() => setTerminalLogs([])}
        browserUrl={browserUrl}
        isLiveServerRunning={isLiveServerRunning}
        onRunLiveServer={() => {
          setIsLiveServerRunning(true);
          setBrowserUrl('http://localhost:5500');
          setActiveAppId('chrome');
        }}
        onNavigateBrowser={(url) => setBrowserUrl(url)}
        automationSteps={automationSteps}
        currentExecutingStepIndex={currentStepIndex}
        isExecuting={isExecuting}
      />
    </div>
  );
}
